-- ============================================================================
-- V16: Create reminder tables (reminder_config + reminder_task)
-- ============================================================================
-- Phase 4: Reminders & System Integration
-- Plan 01: Reminder module foundation
--
-- D-03: Two-table design: reminder_config (type, template, scheduling rules)
--        + reminder_task (per-user instance, status, confirmation time).
-- D-04: 6 reminder types are code-enumerated in ReminderTypeEnum, not DB rows.
-- D-23: Each config stores title (fixed text), body template (with variable
--        placeholders), and urgency level.
-- ============================================================================

-- ── reminder_config ──────────────────────────────────────────────────────────
-- Stores admin-configured reminder type definitions with template, scheduling,
-- and responsible-person rules. One config per type+dept combination.
CREATE TABLE IF NOT EXISTS `reminder_config` (
    `id`                    BIGINT          NOT NULL AUTO_INCREMENT  COMMENT 'Primary key',
    `type_code`             VARCHAR(50)     NOT NULL                 COMMENT 'Reminder type code (maps to ReminderTypeEnum)',
    `achievement_name`      VARCHAR(200)                             COMMENT 'Achievement name — filled by admin; used for template variable {achievementName} substitution',
    `title_template`        VARCHAR(200)    NOT NULL                 COMMENT 'Title template, supports {achievementName} variable',
    `body_template`         TEXT                                     COMMENT 'Body template, supports {achievementName}/{deadline}/{daysRemaining}/{responsiblePerson} variables',
    `urgency`               VARCHAR(10)     NOT NULL DEFAULT 'MEDIUM' COMMENT 'Urgency level: HIGH / MEDIUM / LOW',
    `advance_days`          INT             NOT NULL DEFAULT 30      COMMENT 'Days before deadline to trigger reminder — deadline = today + advance_days unless deadline is explicitly set',
    `deadline`              DATE             NULL                     COMMENT 'Explicit deadline date — when set, overrides advance_days calculation',
    `scheduling_rule`       VARCHAR(100)                             COMMENT 'Cron expression or scheduling rule (optional)',
    `responsible_user_id`   BIGINT                                   COMMENT 'Primary responsible person (user ID)',
    `responsible_role_code` VARCHAR(50)                              COMMENT 'Role code for role-based fallback (e.g. ROLE_SECRETARY)',
    `status`                TINYINT         NOT NULL DEFAULT 1       COMMENT 'Status: 1=enabled, 0=disabled',
    `dept_id`               BIGINT                                   COMMENT 'Department ID for SQL-layer data isolation',
    `created_by`            BIGINT                                   COMMENT 'Creator user ID',
    `created_time`          DATETIME                                 COMMENT 'Creation timestamp',
    `updated_by`            BIGINT                                   COMMENT 'Last updater user ID',
    `updated_time`          DATETIME                                 COMMENT 'Last update timestamp',
    PRIMARY KEY (`id`),
    INDEX `idx_type_code` (`type_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Reminder configuration — type, template, scheduling, and responsible-person rules';

-- ── reminder_task ────────────────────────────────────────────────────────────
-- Stores per-user reminder task instances generated by the daily scheduler.
-- One config can produce many task instances (one per user).
CREATE TABLE IF NOT EXISTS `reminder_task` (
    `id`                    BIGINT          NOT NULL AUTO_INCREMENT  COMMENT 'Primary key',
    `config_id`             BIGINT          NOT NULL                 COMMENT 'FK to reminder_config.id',
    `user_id`               BIGINT          NOT NULL                 COMMENT 'Assigned user ID',
    `achievement_name`      VARCHAR(200)                             COMMENT 'Achievement name for variable substitution',
    `title`                 VARCHAR(200)    NOT NULL                 COMMENT 'Rendered notification title',
    `content`               TEXT                                     COMMENT 'Rendered notification body content',
    `deadline`              DATE            NOT NULL                 COMMENT 'Deadline date this task refers to',
    `days_remaining`        INT             NOT NULL DEFAULT 0       COMMENT 'Days remaining until deadline at generation time',
    `urgency`               VARCHAR(10)     NOT NULL DEFAULT 'MEDIUM' COMMENT 'Urgency level: HIGH / MEDIUM / LOW',
    `confirmed_flag`        TINYINT         NOT NULL DEFAULT 0       COMMENT 'Read receipt flag: 0=unconfirmed, 1=confirmed',
    `confirmed_time`        DATETIME                                 COMMENT 'Timestamp when user confirmed receipt',
    `escalation_level`      VARCHAR(20)     NOT NULL DEFAULT 'NONE'  COMMENT 'Escalation level: NONE / DEPT_HEAD / LEADERSHIP',
    `email_sent_flag`       TINYINT         NOT NULL DEFAULT 0       COMMENT 'Email sent flag: 0=not sent, 1=sent',
    `email_sent_time`       DATETIME                                 COMMENT 'Timestamp when email was sent',
    `email_retry_count`     INT             NOT NULL DEFAULT 0       COMMENT 'Number of email send retry attempts',
    `dept_id`               BIGINT                                   COMMENT 'Department ID for SQL-layer data isolation',
    `created_time`          DATETIME                                 COMMENT 'Creation timestamp',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `idx_unique_task` (`config_id`, `user_id`, `deadline`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_deadline` (`deadline`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Per-user reminder task instances generated by the daily scheduler';
