package com.institute.achievement.fee.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Alert record entity — maps to the {@code alert_record} table (D-20).
 * <p>
 * Records fee payment alerts generated by the daily scan task at 4 AM.
 * Each alert is classified into one of 4 tiers (BLUE / YELLOW / ORANGE / RED)
 * based on due date proximity relative to the scan date.
 * <p>
 * Supports escalation workflow: unresolved alerts can be escalated to
 * department head or leadership (Phase 2 enhancement).
 *
 * @see com.institute.achievement.fee.enums.AlertLevelEnum
 * @see com.institute.achievement.fee.scheduler.AlertScanTask
 */
@Data
@TableName("alert_record")
public class AlertRecord {

    @TableId(type = IdType.AUTO)
    private Long id;

    /** FK to fee_record */
    @TableField("fee_record_id")
    private Long feeRecordId;

    /** Alert level code: BLUE / YELLOW / ORANGE / RED */
    @TableField("alert_level")
    private String alertLevel;

    /** The date of trigger — used for daily dedup */
    @TableField("triggered_date")
    private LocalDate triggeredDate;

    /** Timestamp when the alert was created */
    @TableField("triggered_at")
    private LocalDateTime triggeredAt;

    /** Timestamp when the alert was resolved — nullable */
    @TableField("resolved_at")
    private LocalDateTime resolvedAt;

    /** Alert status: pending, resolved, ignored (default "pending") */
    private String status;

    /**
     * Escalation level: NONE, DEPT_HEAD, LEADERSHIP (default "NONE").
     * Used by the escalation scan task in Phase 2.
     */
    @TableField("escalation_level")
    private String escalationLevel;

    /** Timestamp when escalation was triggered — nullable */
    @TableField("escalated_at")
    private LocalDateTime escalatedAt;

    /** Timestamp when escalation was resolved — nullable */
    @TableField("escalated_resolved_at")
    private LocalDateTime escalatedResolvedAt;

    /** Department ID (for SQL-layer data isolation) */
    @TableField("dept_id")
    private Long deptId;
}
