package com.institute.achievement.fee.entity;

import com.baomidou.mybatisplus.annotation.*;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Fee plan entity — maps to the {@code fee_plan} table.
 * <p>
 * Represents a single fee plan associated with a patent. Plans are either
 * manually created (one-time fees like registration/maintenance) or
 * automatically generated by the daily scheduled task (recurring annual fees).
 * <p>
 * The plan lifecycle is: active → paused (on patent invalidation) or active → deleted (paused only).
 *
 * @see com.institute.achievement.fee.enums.FeePlanStatusEnum
 */
@Data
@TableName("fee_plan")
public class FeePlan {

    @TableId(type = IdType.AUTO)
    private Long id;

    // ── Patent Link ──────────────────────────────────────────────────

    /** FK to patent table (plans are always for patents per D-14) */
    @TableField("patent_id")
    private Long patentId;

    // ── Fee Type ─────────────────────────────────────────────────────

    /** Fee type code — "annual_fee" for recurring, "registration_fee"/"maintenance_fee"/"other" for one-time */
    @TableField("fee_type")
    private String feeType;

    // ── Amount ───────────────────────────────────────────────────────

    /** Fee amount (yuan) — editable by user */
    private BigDecimal amount;

    // ── Dates ────────────────────────────────────────────────────────

    /** Fee due date — system-calculated from authorizationDate, NOT editable per D-17 */
    @TableField("due_date")
    private LocalDate dueDate;

    // ── Status ───────────────────────────────────────────────────────

    /** Plan status — maps to {@link com.institute.achievement.fee.enums.FeePlanStatusEnum} */
    private String status;

    // ── Source ───────────────────────────────────────────────────────

    /** Plan source — "auto_generated" or "manual" */
    private String source;

    // ── Financial ────────────────────────────────────────────────────

    /** Funding source code — configured via data dictionary (FUND_SOURCE) */
    @TableField("funding_source")
    private String fundingSource;

    // ── Department & Ownership ───────────────────────────────────────

    /** Department ID (for SQL-layer data isolation) */
    @TableField("dept_id")
    private Long deptId;

    /** Creator user ID */
    @TableField("created_by")
    private Long createdBy;

    @TableField(fill = FieldFill.INSERT)
    private LocalDateTime createdTime;

    /** Last updater user ID */
    @TableField("updated_by")
    private Long updatedBy;

    @TableField(fill = FieldFill.UPDATE)
    private LocalDateTime updatedTime;
}
