package com.institute.achievement.reminder.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Reminder task entity — maps to the {@code reminder_task} table (D-03).
 * <p>
 * Stores per-user reminder task instances generated by the daily scheduler.
 * Each task is derived from a {@link ReminderConfig} and represents a single
 * to-do item for a specific user with deadline, urgency, confirmation status,
 * escalation level, and email delivery state.
 *
 * <h3>Lifecycle</h3>
 * <ol>
 *   <li>Generated by daily scheduler from enabled {@code reminder_config}</li>
 *   <li>User views in notification center REMINDER tab</li>
 *   <li>User clicks "confirm receipt" → {@code confirmedFlag}=1, {@code confirmedTime}=now</li>
 *   <li>Escalation scheduler checks unconfirmed tasks → escalates if near deadline</li>
 *   <li>Tasks are retained after completion for audit trail (D-07)</li>
 * </ol>
 *
 * @see ReminderConfig
 */
@Data
@TableName("reminder_task")
public class ReminderTask {

    @TableId(type = IdType.AUTO)
    private Long id;

    /** FK to reminder_config.id */
    @TableField("config_id")
    private Long configId;

    /** Assigned user ID */
    @TableField("user_id")
    private Long userId;

    /** Achievement name for variable substitution */
    @TableField("achievement_name")
    private String achievementName;

    /** Rendered notification title */
    private String title;

    /** Rendered notification body content */
    private String content;

    /** Deadline date this task refers to */
    private LocalDate deadline;

    /** Days remaining until deadline at generation time */
    @TableField("days_remaining")
    private Integer daysRemaining;

    /** Urgency level: HIGH / MEDIUM / LOW */
    private String urgency;

    /** Read receipt flag: 0=unconfirmed, 1=confirmed */
    @TableField("confirmed_flag")
    private Integer confirmedFlag;

    /** Timestamp when user confirmed receipt */
    @TableField("confirmed_time")
    private LocalDateTime confirmedTime;

    /** Escalation level: NONE / DEPT_HEAD / LEADERSHIP */
    @TableField("escalation_level")
    private String escalationLevel;

    /** Email sent flag: 0=not sent, 1=sent */
    @TableField("email_sent_flag")
    private Integer emailSentFlag;

    /** Timestamp when email was sent */
    @TableField("email_sent_time")
    private LocalDateTime emailSentTime;

    /** Number of email send retry attempts */
    @TableField("email_retry_count")
    private Integer emailRetryCount;

    /** Department ID (for SQL-layer data isolation) */
    @TableField("dept_id")
    private Long deptId;

    /** Creation timestamp */
    @TableField("created_time")
    private LocalDateTime createdTime;
}
