package com.institute.achievement.attachment.entity;

import com.baomidou.mybatisplus.annotation.*;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Attachment entity — stores metadata for uploaded files.
 * <p>
 * Uses Exclusive Arc pattern (P0-01): exactly one of paperId/patentId/copyrightId
 * is non-null, establishing the polymorphic relationship.
 * <p>
 * File content is stored on the local filesystem; this table only tracks metadata.
 * The stored_name is a UUID generated by the file proxy service (P0-06).
 */
@Data
@TableName("attachment")
public class Attachment {

    @TableId(type = IdType.AUTO)
    private Long id;

    /** Original filename provided by the uploader */
    private String originalName;

    /** UUID-based stored name (generated by file proxy, no direct path exposure) */
    private String storedName;

    /** Relative storage path */
    private String filePath;

    /** File size in bytes */
    private Long fileSize;

    /** MIME type */
    private String fileType;

    // ── Exclusive Arc ──────────────────────────────────────────────

    private Long paperId;
    private Long patentId;
    private Long copyrightId;

    // ── Audit ──────────────────────────────────────────────────────

    private Long uploaderId;

    @TableField(fill = FieldFill.INSERT)
    private LocalDateTime uploadTime;

    // ── Soft Delete ────────────────────────────────────────────────

    private Integer isDeleted;
    private LocalDateTime deletedTime;

    // ── Computed (non-persistent) ──────────────────────────────────

    @TableField(exist = false)
    private String fileSizeDisplay;
}
