-- V13: Create alert_record table
-- Stores 4-tier fee alert records generated by the daily scan task (FEE-03).
-- Each alert is linked to a fee_record via fee_record_id and classified into
-- BLUE (30d), YELLOW (15d), ORANGE (7d), or RED (overdue) levels.
-- Supports escalation workflow for unresolved alerts (Phase 2).
--
-- Design decisions:
-- - D-20: Alert records persisted to alert_record table (separate from notification)
-- - D-22: 4-tier colors: Blue (30d), Yellow (15d), Orange (7d), Red (overdue)
-- - D-25: Alerts delivered via in-app notification only (email deferred to Phase 4)

CREATE TABLE `alert_record` (
    `id`                    BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键ID',

    -- Fee record association
    `fee_record_id`         BIGINT       NOT NULL                COMMENT '关联费用记录ID (FK -> fee_record.id)',

    -- Alert classification (D-22)
    `alert_level`           VARCHAR(20)  NOT NULL                COMMENT '预警级别(BLUE/YELLOW/ORANGE/RED)',

    -- Trigger details
    `triggered_date`        DATE         NOT NULL                COMMENT '触发日期(用于日去重)',
    `triggered_at`          DATETIME     NOT NULL                COMMENT '触发时间',

    -- Resolution
    `resolved_at`           DATETIME     NULL                    COMMENT '解决时间',

    -- Status
    `status`                VARCHAR(20)  NOT NULL DEFAULT 'pending' COMMENT '状态(pending/resolved/ignored)',

    -- Escalation (Phase 2)
    `escalation_level`      VARCHAR(20)  NOT NULL DEFAULT 'NONE' COMMENT '升级等级(NONE/DEPT_HEAD/LEADERSHIP)',
    `escalated_at`          DATETIME     NULL                    COMMENT '升级时间',
    `escalated_resolved_at` DATETIME     NULL                    COMMENT '升级解决时间',

    -- Department & data isolation
    `dept_id`               BIGINT       NOT NULL                COMMENT '所属部门ID',

    PRIMARY KEY (`id`),

    -- FK to fee_record for JOIN queries
    INDEX `idx_fee_record_id` (`fee_record_id`),

    -- Filter pending alerts
    INDEX `idx_status` (`status`),

    -- Daily scan by trigger date
    INDEX `idx_triggered_date` (`triggered_date`),

    -- Escalation queries
    INDEX `idx_escalation` (`escalation_level`, `status`),

    -- Department data isolation
    INDEX `idx_dept_id` (`dept_id`),

    -- Prevents duplicate alerts: same fee_record + same level + same date (T-02-03-01)
    UNIQUE INDEX `idx_unique_alert` (`fee_record_id`, `alert_level`, `triggered_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='预警记录表';
